#!/usr/bin/env python3

from comms.Ultrasonics import Ultrasonics 
from sensor_msgs.msg import Range
import rospy 

if __name__ == "__main__":
    try:
        rospy.init_node("republisher")
        ultrasonics_pub = rospy.Publisher("robot/sensors/ultrasonics",Range,queue_size=10000)
        myUltrasonics = Ultrasonics(0,0x8)

        while not rospy.is_shutdown():
            print(myUltrasonics.get_data()[0])
            ultrasonics_pub.publish(myUltrasonics.get_range_msg())
            rospy.sleep(0.05)
    except rospy.ROSInterruptException:
        pass 
