#!/usr/bin/env python3

import rospy
import RPi.GPIO as GPIO
from control.Move import Move

class Controller():
    def __init__(self):
        rospy.init_node("controller")
        self.move = Move()
        
     
    
if __name__ == '__main__':
    try:
        my_robot = Controller()
        #rospy.spin()
    
    except KeyboardInterrupt: # If CTRL+C is pressed, exit cleanly:
        print("Keyboard interrupt")
    finally:
        GPIO.cleanup() # clear pin config 


